#!/bin/bash
while getopts a:s: option 
do 
case "${option}" 
in 
a) APIHOST="--apihost=${OPTARG}";;
s) SATHOST="--sathost=${OPTARG}";;
esac 
done
gulp clean
gulp server-js
gulp --ccmixter  -p ${APIHOST}
gulp --dig       -p 
gulp --stems     -p ${SATHOST}
gulp --playlists -p ${SATHOST}
gulp --pells     -p ${SATHOST}