#!/bin/bash
set -e
while getopts a:s: option 
do 
case "${option}" 
in 
a) RPCHOST="--rpchost=${OPTARG}";;
s) SATHOST="--sathost=${OPTARG}";;
esac 
done

gulp clean -p

# apps
gulp server-js app -p ${RPCHOST} ${SATHOST}
gulp  --dig        -p ${RPCHOST} ${SATHOST}

# satellites
gulp --stems     -p ${SATHOST}
gulp --playlists -p ${SATHOST}
gulp --pells     -p ${SATHOST}

# move tmp build dir to /dist
gulp publish

