// this file is generated by the build process 

import FeaturedPage from './FeaturedPage';
import Footer from './Footer';
import Header from './Header';
import QueryOptions from './QueryOptions';
import TagSearch from './TagSearch';
import Upload from './Upload';


module.exports = {
    FeaturedPage,
    Footer,
    Header,
    QueryOptions,
    TagSearch,
    Upload 
};

