// this file is generated by the build process 

import Browse from './Browse';
import Detail from './Detail';
import Files from './Files';
import Footer from './Footer';
import Header from './Header';
import Listing from './Listing';
import People from './People';
import QueryOptions from './QueryOptions';
import Tags from './Tags';


module.exports = {
    Browse,
    Detail,
    Files,
    Footer,
    Header,
    Listing,
    People,
    QueryOptions,
    Tags 
};

