// this file is generated by the build process 

import Browse from './Browse';
import Footer from './Footer';
import Header from './Header';
import Info from './Info';
import PlayAllButton from './PlayAllButton';
import Tags from './Tags';
import Tracks from './Tracks';


module.exports = {
    Browse,
    Footer,
    Header,
    Info,
    PlayAllButton,
    Tags,
    Tracks 
};

