// this file is generated by the build process 

import Feed from './Feed';
import FeedSubNav from './FeedSubNav';
import Footer from './Footer';
import Gallery from './Gallery';
import GalleryElement from './GalleryElement';
import GallerySubNav from './GallerySubNav';
import Header from './Header';
import Login from './Login';
import People from './People';


module.exports = {
    Feed,
    FeedSubNav,
    Footer,
    Gallery,
    GalleryElement,
    GallerySubNav,
    Header,
    Login,
    People 
};

