// this file is generated by the build process 

module.exports = { 
  about: require('./about'),
  ccplus: require('./ccplus'),
  dig: require('./dig'),
  edpicks: require('./edpicks'),
  film: require('./film'),
  free: require('./free'),
  games: require('./games'),
  index: require('./indexRoute'),
  licenses: require('./licenses'),
  people: require('./people'),
  search: require('./search'),
  upload: require('./upload'),

};

